### ISSUE TITLE
0.340 failed to pass 20_parse_self.t

### ISSUE THREAD

**Issue by charsbar** [domm/Module-ExtractUse#17]
Hi. Because of the last-minute change (https://github.com/domm/Module-ExtractUse/commit/8b5d1a0324cda53df25a84f8102d3a555c64dfa3), 0.340 doesn't pass its self test. Fixed in https://github.com/domm/Module-ExtractUse/commit/443a8035d010e2f5cda751f3211c0c803ab5bbe5. Could you bump up the version again and ship it?

**Comment by domm** [comment]
Ah, sorry for that...
Fixed version on it's way to CPAN.
Thanks for the quick spot & fix!
